// This file is autogenerated by cmd/generate/main.go
package assettransfers

import (
    "fmt"

	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/atr/v1/cashmanagement-cashwithdrawal/withdrawl/18f26c2a252695ffd0fb62314210bb8c
func Withdrawl(params *WithdrawlParams) (*WithdrawlResponse, error) {
    resp, err := saxo.GetClient().DoRequest("POST", "https://gateway.saxobank.com/sim/openapi/atr/v1/cashmanagement/withdrawals", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    respJson := &WithdrawlResponse{}
    err = resp.ToJSON(respJson)
    if err != nil {
        return nil, err
    }
    return respJson, nil
}

type WithdrawlParams struct { 
    AccountKey string // required
    Amount float64 // required
    BeneficiaryInstructionId string // required
    Currency string // required
    MessageToBeneficiary string 
}
