// This file is autogenerated by cmd/generate/main.go
package clientservices

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cs/v2/clientinfo/search/751324b669928ae0a4dbc8c28c003d03
func Search(params *SearchParams) (*SearchResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/cs/v2/clientinfo/clients/search/?$top={$top}&$skip={$skip}&$inlinecount={$inlinecount}"
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("POST", url, params)
	if err != nil {
		return nil, err
	}
	respJson := &SearchResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type SearchParams struct {
	Inlinecount string `url:",omitempty"`
	Skip        int64  `url:",omitempty"`
	Top         int64  `url:",omitempty"`
	AccountId   string
	AccountKey  string
	ClientId    string
	ClientKey   string
	FieldGroups string
	Keywords    string
	UserId      string
}
