// This file is autogenerated by cmd/generate/main.go
package clientservices

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cs/v1/historicalreportdata-trades/getdetailsasync/530c3d12f21817d3a77911a4644fa0f1
func GetDetailsAsync(clientkey string, params *GetDetailsAsyncParams) (*GetDetailsAsyncResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/cs/v1/reports/trades/{ClientKey}/?$top={$top}&$skip={$skip}&$skiptoken={$skiptoken}&AccountGroupKey={AccountGroupKey}&AccountKey={AccountKey}&FromDate={FromDate}&ToDate={ToDate}&TradeId={TradeId}&MockDataId={MockDataId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{ClientKey}", clientkey))
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetDetailsAsyncResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type GetDetailsAsyncParams struct {
	Skip            int64  `url:",omitempty"`
	Skiptoken       string `url:",omitempty"`
	Top             int64  `url:",omitempty"`
	AccountGroupKey string `url:",omitempty"`
	AccountKey      string `url:",omitempty"`
	FromDate        string `url:",omitempty"`
	MockDataId      string `url:",omitempty"`
	ToDate          string `url:",omitempty"`
	TradeId         string `url:",omitempty"`
}
