// This file is autogenerated by cmd/generate/main.go
package clientservices

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cs/v1/historicalreportdata-bookings/get/29d0de16ec94dac98d5253d314cd14bc
func GetBookings(clientkey string, params *GetBookingsParams) (*GetBookingsResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/cs/v1/reports/bookings/{ClientKey}/?$top={$top}&$skip={$skip}&$skiptoken={$skiptoken}&AccountGroupKey={AccountGroupKey}&AccountKey={AccountKey}&FilterType={FilterType}&FilterValue={FilterValue}&FromDate={FromDate}&ToDate={ToDate}&MockDataId={MockDataId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{ClientKey}", clientkey))
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetBookingsResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type GetBookingsParams struct {
	Skip            int64  `url:",omitempty"`
	Skiptoken       string `url:",omitempty"`
	Top             int64  `url:",omitempty"`
	AccountGroupKey string `url:",omitempty"`
	AccountKey      string `url:",omitempty"`
	FilterType      string `url:",omitempty"`
	FilterValue     string `url:",omitempty"`
	FromDate        string `url:",omitempty"`
	MockDataId      string `url:",omitempty"`
	ToDate          string `url:",omitempty"`
}
