// This file is autogenerated by cmd/generate/main.go
package clientservices

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cs/v1/historicalreportdata-aggregatedamounts/get/3962da8f9c349b9c3646548a669c169e
func GetAggregatedAmounts(clientkey string, fromdate string, todate string, params *GetAggregatedAmountsParams) (*GetAggregatedAmountsResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/cs/v1/reports/aggregatedAmounts/{ClientKey}/{FromDate}/{ToDate}/?$top={$top}&$skip={$skip}&$skiptoken={$skiptoken}&AccountGroupKey={AccountGroupKey}&AccountKey={AccountKey}&MockDataId={MockDataId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{ClientKey}", clientkey), saxo.RP("{FromDate}", fromdate), saxo.RP("{ToDate}", todate))
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetAggregatedAmountsResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type GetAggregatedAmountsParams struct {
	Skip            int64  `url:",omitempty"`
	Skiptoken       string `url:",omitempty"`
	Top             int64  `url:",omitempty"`
	AccountGroupKey string `url:",omitempty"`
	AccountKey      string `url:",omitempty"`
	MockDataId      string `url:",omitempty"`
}
