// This file is autogenerated by cmd/generate/main.go
package clientservices

import (
    "fmt"

	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cs/v1/historicalreportdata-aggregatedamounts/get/3962da8f9c349b9c3646548a669c169e
func GetAggregatedAmounts(clientkey string, fromdate string, todate string, params *GetAggregatedAmountsParams) (*GetAggregatedAmountsResponse, error) {
    resp, err := saxo.GetClient().DoRequest("GET", "https://gateway.saxobank.com/sim/openapi/cs/v1/reports/aggregatedAmounts/{ClientKey}/{FromDate}/{ToDate}/?$top={$top}&$skip={$skip}&$skiptoken={$skiptoken}&AccountGroupKey={AccountGroupKey}&AccountKey={AccountKey}&MockDataId={MockDataId}", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    respJson := &GetAggregatedAmountsResponse{}
    err = resp.ToJSON(respJson)
    if err != nil {
        return nil, err
    }
    return respJson, nil
}

type GetAggregatedAmountsParams struct { 
    skip int64
    skiptoken string
    top int64
    AccountGroupKey string
    AccountKey string
    
    
    MockDataId string
     
}
