// This file is autogenerated by cmd/generate/main.go
package trading

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/trade/v1/allocationkeys/getallocationkeys/43a2f548b96be1dfa18b3a7cfaf6bb89
func GetAllocationKeys(params *GetAllocationKeysParams) (*GetAllocationKeysResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/trade/v1/allocationkeys/?$top={$top}&$skip={$skip}&AccountKey={AccountKey}&ClientKey={ClientKey}&Statuses={Statuses}"
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetAllocationKeysResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type GetAllocationKeysParams struct {
	Skip       int64  `url:",omitempty"`
	Top        int64  `url:",omitempty"`
	AccountKey string `url:",omitempty"`
	ClientKey  string `url:",omitempty"`
	Statuses   string `url:",omitempty"`
}

// https://www.developer.saxo/openapi/referencedocs/trade/v1/allocationkeys/getallocationkey/6c3cf06c46f41128f215ed9f9a73a676
func GetAllocationKey(allocationkeyid string) (*GetAllocationKeyResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/trade/v1/allocationkeys/{AllocationKeyId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{AllocationKeyId}", allocationkeyid))
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetAllocationKeyResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

// https://www.developer.saxo/openapi/referencedocs/trade/v1/allocationkeys/distributeamountaccordingtoallocationkey/db4cff5278249a4e3d8b99f49690d5fb
func DistributeAmountAccordingToAllocationKey(allocationkeyid string, params *DistributeAmountAccordingToAllocationKeyParams) (*DistributeAmountAccordingToAllocationKeyResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/trade/v1/allocationkeys/distributions/{AllocationKeyId}/?Totalamount={Totalamount}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{AllocationKeyId}", allocationkeyid))
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &DistributeAmountAccordingToAllocationKeyResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type DistributeAmountAccordingToAllocationKeyParams struct {
	Totalamount string `url:",omitempty"`
}

// https://www.developer.saxo/openapi/referencedocs/trade/v1/allocationkeys/addallocationkey/324a07c660d07971519f57d72bff1ea9
func AddAllocationKey(params *AddAllocationKeyParams) (*AddAllocationKeyResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/trade/v1/allocationkeys"
	resp, err := saxo.GetClient().DoRequest("POST", url, params)
	if err != nil {
		return nil, err
	}
	respJson := &AddAllocationKeyResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type AddAllocationKeyParams struct {
	AllocationKeyName         string // required
	AllocationUnitType        string // required
	MarginHandling            string // required
	OneTime                   bool   // required
	OwnerAccountKey           string // required
	ParticipatingAccountsInfo string // required
}

// https://www.developer.saxo/openapi/referencedocs/trade/v1/allocationkeys/deleteallocationkey/4186abc67c861a502ba1f26c9519dd1a
func DeleteAllocationKey(allocationkeyid string) ([]byte, error) {
	url := "https://gateway.saxobank.com/sim/openapi/trade/v1/allocationkeys/{AllocationKeyId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{AllocationKeyId}", allocationkeyid))
	resp, err := saxo.GetClient().DoRequest("DELETE", url, nil)
	if err != nil {
		return nil, err
	}
	return resp.Bytes(), nil
}
