// This file is autogenerated by cmd/generate/main.go
package referencedata

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/ref/v1/currencies/getcurrencies/1f05ea6284a3c690ec54a26051e3d055
func GetCurrencies() (*GetCurrenciesResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/ref/v1/currencies"
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetCurrenciesResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}
