// This file is autogenerated by cmd/generate/main.go
package referencedata

import (
    "fmt"

	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/ref/v1/standarddates/getforwardtenordates/f3b91ed5e08e1d663c7a33bf045df567
func GetForwardTenorDates(uic string, params *GetForwardTenorDatesParams) (*GetForwardTenorDatesResponse, error) {
    resp, err := saxo.GetClient().DoRequest("GET", "https://gateway.saxobank.com/sim/openapi/ref/v1/standarddates/forwardtenor/{Uic}/?AccountKey={AccountKey}", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    respJson := &GetForwardTenorDatesResponse{}
    err = resp.ToJSON(respJson)
    if err != nil {
        return nil, err
    }
    return respJson, nil
}

type GetForwardTenorDatesParams struct { 
    AccountKey string
     
}

// https://www.developer.saxo/openapi/referencedocs/ref/v1/standarddates/getfxoptionexpirydates/be7b3c6935a397693069a0529b2c7490
func GetFxOptionExpiryDates(uic string) (*GetFxOptionExpiryDatesResponse, error) {
    resp, err := saxo.GetClient().DoRequest("GET", "https://gateway.saxobank.com/sim/openapi/ref/v1/standarddates/fxoptionexpiry/{Uic}", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    respJson := &GetFxOptionExpiryDatesResponse{}
    err = resp.ToJSON(respJson)
    if err != nil {
        return nil, err
    }
    return respJson, nil
}

