package portfolio

type GetOpenOrderDetailsResponse struct {
	AccountID        string `json:"AccountId"`
	AccountKey       string `json:"AccountKey"`
	AlgoOrderDetails struct {
		Key2ed5fdca_3d9e_4dd7_a2f6_9250728bc956 string `json:"key2ed5fdca-3d9e-4dd7-a2f6-9250728bc956"`
	} `json:"AlgoOrderDetails"`
	AlgoStrategyName        string  `json:"AlgoStrategyName"`
	Amount                  float64 `json:"Amount"`
	AmountAccountValueRatio string  `json:"AmountAccountValueRatio"`
	ApprovalState           struct {
		ApprovalExpiryTime string `json:"ApprovalExpiryTime"`
		ApprovalType       string `json:"ApprovalType"`
		ExternalReference  string `json:"ExternalReference"`
		State              string `json:"State"`
	} `json:"ApprovalState"`
	Ask                      float64  `json:"Ask"`
	AssetType                string   `json:"AssetType"`
	Bid                      float64  `json:"Bid"`
	BreakoutTriggerDownPrice float64  `json:"BreakoutTriggerDownPrice"`
	BreakoutTriggerUpPrice   float64  `json:"BreakoutTriggerUpPrice"`
	BuySell                  string   `json:"BuySell"`
	CalculationReliability   string   `json:"CalculationReliability"`
	CashAmount               float64  `json:"CashAmount"`
	ClientID                 string   `json:"ClientId"`
	ClientKey                string   `json:"ClientKey"`
	ClientName               string   `json:"ClientName"`
	CopiedPositionID         string   `json:"CopiedPositionId"`
	CorrelationKey           string   `json:"CorrelationKey"`
	CorrelationTypes         []string `json:"CorrelationTypes"`
	CurrentPrice             float64  `json:"CurrentPrice"`
	CurrentPriceDelayMinutes float64  `json:"CurrentPriceDelayMinutes"`
	CurrentPriceLastTraded   string   `json:"CurrentPriceLastTraded"`
	CurrentPriceType         string   `json:"CurrentPriceType"`
	DecisionMakerUserID      string   `json:"DecisionMakerUserId"`
	DisplayAndFormat         struct {
		BarrierDecimals                 float64 `json:"BarrierDecimals"`
		BarrierFormat                   string  `json:"BarrierFormat"`
		Currency                        string  `json:"Currency"`
		Decimals                        float64 `json:"Decimals"`
		Description                     string  `json:"Description"`
		DisplayHint                     string  `json:"DisplayHint"`
		Format                          string  `json:"Format"`
		NumeratorDecimals               float64 `json:"NumeratorDecimals"`
		OrderDecimals                   float64 `json:"OrderDecimals"`
		StrikeDecimals                  float64 `json:"StrikeDecimals"`
		StrikeFormat                    string  `json:"StrikeFormat"`
		Symbol                          string  `json:"Symbol"`
		UnderlyingInstrumentDescription string  `json:"UnderlyingInstrumentDescription"`
	} `json:"DisplayAndFormat"`
	DistanceToMarket float64 `json:"DistanceToMarket"`
	Duration         struct {
		DurationType               string `json:"DurationType"`
		ExpirationDate             string `json:"ExpirationDate"`
		ExpirationDateContainsTime bool   `json:"ExpirationDateContainsTime"`
		ExpirationDateTime         string `json:"ExpirationDateTime"`
	} `json:"Duration"`
	Exchange struct {
		Description string `json:"Description"`
		ExchangeID  string `json:"ExchangeId"`
		IsOpen      bool   `json:"IsOpen"`
		TimeZoneID  string `json:"TimeZoneId"`
	} `json:"Exchange"`
	ExpiryDate        string  `json:"ExpiryDate"`
	ExternalReference string  `json:"ExternalReference"`
	FilledAmount      float64 `json:"FilledAmount"`
	Greeks            struct {
		Delta           float64 `json:"Delta"`
		DeltaCurrency   string  `json:"DeltaCurrency"`
		Gamma           float64 `json:"Gamma"`
		GammaCurrency   string  `json:"GammaCurrency"`
		InstrumentDelta float64 `json:"InstrumentDelta"`
		InstrumentGamma float64 `json:"InstrumentGamma"`
		InstrumentTheta float64 `json:"InstrumentTheta"`
		InstrumentVega  float64 `json:"InstrumentVega"`
		MidVol          float64 `json:"MidVol"`
		Phi             float64 `json:"Phi"`
		Rho             float64 `json:"Rho"`
		Theta           float64 `json:"Theta"`
		ThetaCurrency   string  `json:"ThetaCurrency"`
		Vega            float64 `json:"Vega"`
		VegaCurrency    string  `json:"VegaCurrency"`
	} `json:"Greeks"`
	IsForceOpen          bool    `json:"IsForceOpen"`
	IsMarketOpen         bool    `json:"IsMarketOpen"`
	Isin                 string  `json:"Isin"`
	MarketPrice          float64 `json:"MarketPrice"`
	MarketState          string  `json:"MarketState"`
	MarketValue          float64 `json:"MarketValue"`
	MultiLegOrderDetails struct {
		Amount           float64 `json:"Amount"`
		BuySell          string  `json:"BuySell"`
		CurrentPrice     float64 `json:"CurrentPrice"`
		Description      string  `json:"Description"`
		DistanceToMarket float64 `json:"DistanceToMarket"`
		FilledAmount     float64 `json:"FilledAmount"`
		LegCount         float64 `json:"LegCount"`
		MultiLegOrderID  string  `json:"MultiLegOrderId"`
		Price            float64 `json:"Price"`
		StrategyType     string  `json:"StrategyType"`
	} `json:"MultiLegOrderDetails"`
	NonTradableReason string  `json:"NonTradableReason"`
	OpenInterest      float64 `json:"OpenInterest"`
	OpenOrderType     string  `json:"OpenOrderType"`
	OptionsData       struct {
		Barrier                float64 `json:"Barrier"`
		BarrierLower           float64 `json:"BarrierLower"`
		BarrierUpper           float64 `json:"BarrierUpper"`
		ExpiryDate             string  `json:"ExpiryDate"`
		FinancingLevel         float64 `json:"FinancingLevel"`
		Gearing                float64 `json:"Gearing"`
		Moneyness              float64 `json:"Moneyness"`
		PutCall                string  `json:"PutCall"`
		Ratio                  float64 `json:"Ratio"`
		SpreadStrikePriceLower float64 `json:"SpreadStrikePriceLower"`
		SpreadStrikePriceUpper float64 `json:"SpreadStrikePriceUpper"`
		StopLossLevel          float64 `json:"StopLossLevel"`
		Strike                 float64 `json:"Strike"`
		TradePerspective       string  `json:"TradePerspective"`
	} `json:"OptionsData"`
	OrderAmountType    string  `json:"OrderAmountType"`
	OrderID            string  `json:"OrderId"`
	OrderRelation      string  `json:"OrderRelation"`
	OrderTime          string  `json:"OrderTime"`
	OwnerID            string  `json:"OwnerId"`
	Price              float64 `json:"Price"`
	PriceWithoutSpread float64 `json:"PriceWithoutSpread"`
	RelatedOpenOrders  []struct {
		Amount   float64 `json:"Amount"`
		Duration struct {
			DurationType               string `json:"DurationType"`
			ExpirationDate             string `json:"ExpirationDate"`
			ExpirationDateContainsTime bool   `json:"ExpirationDateContainsTime"`
			ExpirationDateTime         string `json:"ExpirationDateTime"`
		} `json:"Duration"`
		OpenOrderType                string  `json:"OpenOrderType"`
		OrderID                      string  `json:"OrderId"`
		OrderPrice                   float64 `json:"OrderPrice"`
		Status                       string  `json:"Status"`
		StopLimitPrice               float64 `json:"StopLimitPrice"`
		TrailingStopDistanceToMarket float64 `json:"TrailingStopDistanceToMarket"`
		TrailingStopStep             float64 `json:"TrailingStopStep"`
	} `json:"RelatedOpenOrders"`
	RelatedPositionID            string  `json:"RelatedPositionId"`
	ShortTrading                 string  `json:"ShortTrading"`
	Status                       string  `json:"Status"`
	StopLimitPrice               float64 `json:"StopLimitPrice"`
	SwitchInstrumentUic          float64 `json:"SwitchInstrumentUic"`
	ToOpenClose                  string  `json:"ToOpenClose"`
	TradeIdeaID                  string  `json:"TradeIdeaId"`
	TradingStatus                string  `json:"TradingStatus"`
	TrailingStopDistanceToMarket float64 `json:"TrailingStopDistanceToMarket"`
	TrailingStopStep             float64 `json:"TrailingStopStep"`
	TriggerParentOrderID         string  `json:"TriggerParentOrderId"`
	TriggerPriceType             string  `json:"TriggerPriceType"`
	Uic                          float64 `json:"Uic"`
	ValueDate                    string  `json:"ValueDate"`
}
