// This file is autogenerated by cmd/generate/main.go
package root

import (
    "fmt"

	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/root/v1/subscriptions/deletesubscriptions/14d1d2d03f6aca45ab9c29e38973f449
func DeleteSubscriptions(contextid string, params *DeleteSubscriptionsParams) ([]byte, error) {
    resp, err := saxo.GetClient().DoRequest("DELETE", "https://gateway.saxobank.com/sim/openapi/root/v1/subscriptions/{ContextId}/?Tag={Tag}", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    return resp.Bytes(), nil 
}

type DeleteSubscriptionsParams struct { 
    
    Tag string 
}
