// This file is autogenerated by cmd/generate/main.go
package clientmanagement

import (
    "fmt"

	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cm/v1/users/resetpassword/9f8c2cf85499f04f15adf43e76bf073a
func ResetPassword(params *ResetPasswordParams) ([]byte, error) {
    resp, err := saxo.GetClient().DoRequest("POST", "https://gateway.saxobank.com/sim/openapi/cm/v1/users/resetpasswordrequest", nil) 
    if err != nil {
        return nil, err
    } else if sc := resp.Response().StatusCode; sc >= 300 {
		return nil, fmt.Errorf("unexpected status code %d", sc)
	}
    return resp.Bytes(), nil 
}

type ResetPasswordParams struct { 
    Email string // required
    Language string
    UserId string // required 
}
