// This file is autogenerated by cmd/generate/main.go
package clientmanagement

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/cm/v1/users/resetpassword/9f8c2cf85499f04f15adf43e76bf073a
func ResetPassword(params *ResetPasswordParams) ([]byte, error) {
	url := "https://gateway.saxobank.com/sim/openapi/cm/v1/users/resetpasswordrequest"
	resp, err := saxo.GetClient().DoRequest("POST", url, params)
	if err != nil {
		return nil, err
	}
	return resp.Bytes(), nil
}

type ResetPasswordParams struct {
	Email    string // required
	Language string
	UserId   string // required
}
