// This file is autogenerated by cmd/generate/main.go
package ens

import (
	"github.com/cborum/go-saxo"
)

// https://www.developer.saxo/openapi/referencedocs/ens/v1/clientactivities/addsubscriptionasync/0d98475e6ff38b2de76b66426008fd4a
func AddSubscriptionAsync(params *AddSubscriptionAsyncParams) (*AddSubscriptionAsyncResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/ens/v1/activities/subscriptions"
	resp, err := saxo.GetClient().DoRequest("POST", url, params)
	if err != nil {
		return nil, err
	}
	respJson := &AddSubscriptionAsyncResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type AddSubscriptionAsyncParams struct {
	Arguments   string // required
	ContextId   string // required
	Format      string
	ReferenceId string // required
	RefreshRate int64
	Tag         string
}

// https://www.developer.saxo/openapi/referencedocs/ens/v1/clientactivities/deletesubscription/650d599c8e65c2fee9c3884ff66af1ba
func DeleteSubscription(contextid string, referenceid string) ([]byte, error) {
	url := "https://gateway.saxobank.com/sim/openapi/ens/v1/activities/subscriptions/{ContextId}/{ReferenceId}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{ContextId}", contextid), saxo.RP("{ReferenceId}", referenceid))
	resp, err := saxo.GetClient().DoRequest("DELETE", url, nil)
	if err != nil {
		return nil, err
	}
	return resp.Bytes(), nil
}

// https://www.developer.saxo/openapi/referencedocs/ens/v1/clientactivities/deletesubscriptions/b413ff7923a8fef648420ac76f1b1a86
func DeleteSubscriptions(contextid string, params *DeleteSubscriptionsParams) ([]byte, error) {
	url := "https://gateway.saxobank.com/sim/openapi/ens/v1/activities/subscriptions/{ContextId}/?Tag={Tag}"
	url = saxo.PrepareUrlRoute(url, saxo.RP("{ContextId}", contextid))
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("DELETE", url, nil)
	if err != nil {
		return nil, err
	}
	return resp.Bytes(), nil
}

type DeleteSubscriptionsParams struct {
	Tag string `url:",omitempty"`
}

// https://www.developer.saxo/openapi/referencedocs/ens/v1/clientactivities/getactivitiesasync/873a0cb82bf75890b4929f38e2de2b6b
func GetActivitiesAsync(params *GetActivitiesAsyncParams) (*GetActivitiesAsyncResponse, error) {
	url := "https://gateway.saxobank.com/sim/openapi/ens/v1/activities/?$top={$top}&$skiptoken={$skiptoken}&OrderStatuses={OrderStatuses}&OrderTypes={OrderTypes}&Duration={Duration}&ExpirationDateTime={ExpirationDateTime}&ClientKey={ClientKey}&AccountKey={AccountKey}&AccountGroupKey={AccountGroupKey}&IncludeSubAccounts={IncludeSubAccounts}&FromDateTime={FromDateTime}&ToDateTime={ToDateTime}&Activities={Activities}&SequenceId={SequenceId}&FieldGroups={FieldGroups}&PositionEventFilter={PositionEventFilter}"
	url = saxo.PrepareUrlParams(url, params)
	resp, err := saxo.GetClient().DoRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	respJson := &GetActivitiesAsyncResponse{}
	err = resp.ToJSON(respJson)
	if err != nil {
		return nil, err
	}
	return respJson, nil
}

type GetActivitiesAsyncParams struct {
	Skiptoken           string `url:",omitempty"`
	Top                 int64  `url:",omitempty"`
	AccountGroupKey     string `url:",omitempty"`
	AccountKey          string `url:",omitempty"`
	Activities          string // required
	ClientKey           string `url:",omitempty"`
	Duration            string `url:",omitempty"`
	ExpirationDateTime  string `url:",omitempty"`
	FieldGroups         string `url:",omitempty"`
	FromDateTime        string `url:",omitempty"`
	IncludeSubAccounts  bool   `url:",omitempty"`
	OrderStatuses       string `url:",omitempty"`
	OrderTypes          string `url:",omitempty"`
	PositionEventFilter string `url:",omitempty"`
	SequenceId          string `url:",omitempty"`
	ToDateTime          string `url:",omitempty"`
}
